name: Python Example with pytest
on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  deployments: write
  packages: write

jobs:
  benchmark:
    name: Run pytest-benchmark benchmark
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Download test data
        run: gh release download release -R platomo/OpenTrafficCam-testdata -D tests/data
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Unzip test data
        run: |
          cd tests/data
          unzip \*.zip
          rm *.zip
          cd ..
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
          fi
          if [ -f "requirements-dev.txt" ]; then
              pip install -r requirements-dev.txt
          fi
      - name: Run benchmark tests
        run: pytest ./tests/benchmark_otanalytics.py --benchmark-json output.json
      - name: Store benchmark result - separate results repo
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: output.json
          github-token: ${{ secrets.OTANALYTICS_GITHUBPAGE_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          gh-repository: 'github.com/OpenTrafficCam/OTAnalytics_Page.github.io'
