---
name: Build Nightly Version

on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  publish:
    needs: test
    name: Do a test run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
