---
name: Tests

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  test:
    name: Run Python tests on multiple OS and Python versions
    strategy:
      fail-fast: True
      matrix:
        os: [ubuntu-latest, windows-latest]
        py: ["3.11"]
    uses: 'platomo/GitHub-workflows/.github/workflows/reusable-python-tests.yml@main'
    with:
      os: ${{ matrix.os }}
      py-version: ${{ matrix.py }}
      test_path: OTAnalytics
